services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hexlet
      POSTGRES_USER: hexlet_user
      POSTGRES_PASSWORD: hexlet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hexlet_network

networks:
  hexlet_network:
    driver: bridge

volumes:
  postgres_data: